### ISSUE TITLE
Add support for libsixel protocol for displaying images.

### ISSUE THREAD

**Issue by sadiksaifi** [soystemd/lfutils#2]
- As we all know ueberzug is dead, I guess it would be better if you start offering libsixel support for displaying images in lf.
- Now days libsixel is being supported by so many terminals like [foot](https://codeberg.org/dnkl/foot) terminal.

**Comment by demurky** [comment]
I think it's about time to consider this project dead, as I don't care about lf and terminal image drawing anymore.
